### ISSUE TITLE
Error installing open_spiel on colab

### ISSUE THREAD

**Issue by SwiftGodDev** [werner-duvaud/muzero-general#112]
I tried training a model on google colab. But it gave me this error.

2021-01-12 18:31:27,775	ERROR worker.py:980 -- Possible unhandled error from worker: ray::Trainer.__init__() (pid=67833, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/content/drive/My Drive/muzero-general-master/trainer.py", line 28, in __init__
    self.model.to(torch.device("cuda" if self.config.train_on_gpu else "cpu"))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by ahainaut** [comment]
Hi @SwiftGodDev,
I didn't have any issue training muzero with the [notebook of the repository](https://github.com/werner-duvaud/muzero-general/blob/master/notebook.ipynb). Could you give more details about the configuration you used so I can try to reproduce the error ?

**Comment by SwiftGodDev** [comment]
Hi ahainaut,
Apparently there is no error in your code. I wanted to train a model for chess so I used this repo.
https://github.com/goshawk22/muzero-general

There is some error in his muzero.py file or chess.py file, I guess.
Please check those.

**Comment by goshawk22** [comment]
Did you make sure to enable GPU in the notebook. By default there is only CPU and no GPU acceleration.
It all worked on my GPU but I didn't test it on Colab.

**Comment by SwiftGodDev** [comment]
I dont have a GPU so I ran it on colab and yes my runtime was GPU enabled.

**Comment by goshawk22** [comment]
That version is not functional yet - I never got round to finishing it. 
Sorry I thought you were using the open_spiel wrapper I made. That is fully working and I made a PR.

**Comment by SwiftGodDev** [comment]
How do I use it?

**Comment by goshawk22** [comment]
There is information in the spiel.py game file.

**Comment by SwiftGodDev** [comment]
where is it located?

**Comment by SwiftGodDev** [comment]
Got it.

**Comment by SwiftGodDev** [comment]
But there is no file named spiel.py in games folder

**Comment by goshawk22** [comment]
Look at the spiel branch.

**Comment by SwiftGodDev** [comment]
Got it. Thank you

**Comment by SwiftGodDev** [comment]
I am not able to install open_spiel on colab.

 Building wheel for open-spiel (setup.py) ... error
  ERROR: Failed building wheel for open-spiel
  Running setup.py clean for open-spiel
Failed to build open-spiel
Installing collected packages: open-spiel
    Running setup.py install for open-spiel ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uankco1j/open-spiel_9e590da322794498aba0b8db392d3601/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uankco1j/open-spiel_9e590da322794498aba0b8db392d3601/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-41vf_m7t/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/open-spiel Check the logs for full command output.

**Comment by SwiftGodDev** [comment]
I used the file you said but it still gives the same error.

**Comment by SwiftGodDev** [comment]
Error solved guys, finally.
