### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by theword** [werner-duvaud/muzero-general#139]
<pre>2021-03-19 00:04:00,443.ERROR worker.py:1037 -- Possible unhandled error from worker: <font color="#06989A">ray::Trainer.continuous_update_weights()</font> (pid=24804, ip=192.168.1.229)
  File &quot;python/ray/_raylet.pyx&quot;, line 482, in ray._raylet.execute_task
  File &quot;python/ray/_raylet.pyx&quot;, line 436, in ray._raylet.execute_task.function_executor
  File &quot;/home/john/muzero-general/trainer.py&quot;, line 80, in continuous_update_weights
    ) = self.update_weights(batch)
  File &quot;/home/john/muzero-general/trainer.py&quot;, line 168, in update_weights
    observation_batch
  File &quot;/home/john/muzero-general/models.py&quot;, line 598, in initial_inference
    encoded_state = self.representation(observation)
  File &quot;/home/john/muzero-general/models.py&quot;, line 523, in representation
    encoded_state = self.representation_network(observation)
  File &quot;/home/john/.local/lib/python3.6/site-packages/torch/nn/modules/module.py&quot;, line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File &quot;/home/john/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py&quot;, line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File &quot;/home/john/.local/lib/python3.6/site-packages/torch/nn/modules/module.py&quot;, line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File &quot;/home/john/muzero-general/models.py&quot;, line 343, in forward
    x = self.conv(x)
  File &quot;/home/john/.local/lib/python3.6/site-packages/torch/nn/modules/module.py&quot;, line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File &quot;/home/john/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py&quot;, line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File &quot;/home/john/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py&quot;, line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
</pre>

Running the code in Windows WSL & Ubuntu 18.04 both return the same result. Have tried with Nvidia drivers 440, 450 and 460 series. The CPU task run but this error gets returned for the GPU. Tried to duplicate in Google Co-lab but after the training message, the code just stalls and never displays the training step messages. 

I ran this code and look good in torch. It is installing torch 1.8 (as the requirements.txt file) 

import torch
print(torch.backends.cuda.is_built())
True
print(torch.backends.cudnn.version())
7605
print(torch.backends.cudnn.is_available())
True
print(torch.backends.cudnn.enabled)
True

**EDIT**

This was my orginal message but then I realized that this code probably had an older version of pytorch. Sure enough pytorch 1.7.1 worked. So I have changed the title to "Code does not work in pytorch 1.8". 

**EDIT 2** 

Error appears to be related to Cuda 10.2 (not pytorch 1.8)

**Comment by werner-duvaud** [comment]
Hi,

In colab it works fine for me with the [notebook](https://github.com/werner-duvaud/muzero-general/blob/master/notebook.ipynb) without modification with `torch 1.8.0 + cu101` and `cudnn 7603` (defaults).
The results appear directly in TensorBoard and we do not print the results.

It also works natively under windows (without WSL) and under linux for me.
Check that you have correctly installed the components (cuda toolkit, cudnn, corresponding pytorch version) and that you set the `Path` and `CUDA_PATH` environment variables.

**Comment by theword** [comment]
Hi,

First of all, thank you for the project, it's been amazing to learn from! 

Installing the cuda toolkit & cudnn is unnecessary as those are packaged in with pytorch. The only component you need to install separately is the Nvidia driver. You don't even need to update the path, CUDA_PATH or LD_LIBRARY_PATH. pyTorch ignores your system components and uses the components packaged with torch. 

In the requirements file, you have only 'torch' which corresponds to CUDA 10.2. 

https://pytorch.org/get-started/locally/

If I downgrade torch or add torch+cu101 or torch+cu111, the code then works. I'm led to believe that the code does not work with cuda 10.2 because when I do only pip install torch, it returns the CUDNN_STATUS_NOT_INITIALIZED error. The pip install requirements works in Colab because pytorch 1.8+cu101 is already installed so it does not overwrite with pytorch 1.8+cu102. However, whenever I try to run the tensoboard in Colab, it returns a red arrow and does not display anything even though the muzero.py code runs. 

In essence, the code does not work out of the box for me because pip install -r requirements.txt is installing pytorch with cuda 10.2. It's probably related to the Nvidia drivers but I have tried many.

**Comment by werner-duvaud** [comment]
Yes sorry, I had in mind to compile torch.

I'll investigate what's going on with cuda 10.2.

**Comment by werner-duvaud** [comment]
There doesn't seem to be a version precompiled with cuda 10.2 and torch 1.8 here https://download.pytorch.org/whl/torch_stable.html

This is confirmed by this:
```
pip install torch==1.8.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html                                            
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.0+cu102
ERROR: No matching distribution found for torch==1.8.0+cu102
```

In all cases, in colab, by making
```
pip uninstall torch
pip install -r requirements.txt
```
which uninstall torch-1.8.0+cu101
and install instead the version that you should get with the default installation of the code out of the box.
It runs without error in my colab with GPU enable (tested with fullyconnected and resnet).

**Comment by theword** [comment]
The default 'torch' version is precompiled with cuda 10.2. 

<img width="872" alt="Screen Shot 2021-03-20 at 15 12 50" src="https://user-images.githubusercontent.com/1483287/111885590-5509d080-898e-11eb-8a24-d062d3fab81b.png">

To recreate the erorr in Co-lab

`!pip3 uninstall torch`
`!git clone https://github.com/werner-duvaud/muzero-general.git`
`!pip3 install -r muzero-general/requirements.txt`
`!python3 muzero-general/muzero.py`

I tired tic tac toe and cartpole with train - 

<img width="929" alt="Screen Shot 2021-03-20 at 15 15 11" src="https://user-images.githubusercontent.com/1483287/111885638-a914b500-898e-11eb-9f4a-8f33ad8fabfa.png">

**Comment by werner-duvaud** [comment]
Thanks, I managed to reproduce.

The problem seems to be recent and to come from Pytorch.
The nightly 1.8 and 1.9 version work.
If you need pytorch 1.8 with cu102, this wheel works in colab:

`pip install https://download.pytorch.org/whl/nightly/cu102/torch-1.8.0.dev20210210-cp37-cp37m-linux_x86_64.whl`

and for pytorch 1.9:
`pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html`

I think the problem will be fixed soon https://github.com/pytorch/pytorch/issues/53336 .

**Comment by theword** [comment]
Yup, it seems pyTorch 1.8 with Cuda 10.2 on Turning GPUs is the culprit. 

Thanks for all your help! 

(I'll leave the issue open for now until pytorch officially releases a patch in case someone else comes along with this issue. But of course your discretion )

**Comment by werner-duvaud** [comment]
Pytorch 1.8.1 has been released, there should be no problem with local installation.

On colab, we have to wait for them to update the default preinstalled Pytorch version from 1.8.0 to 1.8.1.

The problem is now restricted to colab only, to fix it until the update:
```
!pip uninstall torch
!pip install -r requirements.txt
```

**Comment by theword** [comment]
wow, the pytorch team is fast. They have resolved the bug and everything works as expected. I will close the issue.

**Comment by execptionerror** [comment]
[Already Solved RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED](RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED)

**Comment by 15066952332** [comment]
good，when I use torch1.8.1，the problem is solved，thanks a lot！！
